### ISSUE TITLE
Feature Request: range and/or split functions

### ISSUE THREAD

**Issue by Luftzig** [elm-community/intdict#10]
I would like to have the following feature: partition around a key, or between two keys. The API I expect is:
`split : Int -> IntDict a -> (IntDict a, IntDict a)` -> works similarly to `partition` but returns all keys with value less than parameter on first dictionary, and all values with greater or equal on the other.
Should be the efficient equivalent of `IntDict.partition (\i _ -> i < pivot) d`

`range : Int -> Int -> IntDict a  -> IntDict a` - will return an IntDict with only the keys between the first argument to the last argument. `range` can be easily implemented using `split`.

**Comment by sgraf812** [comment]
Sounds reasonable. I'd accept a PR for that :)

**Comment by Luftzig** [comment]
Ok, so I'll get working on that.

**Comment by Luftzig** [comment]
This pull request has a bug that is reproduced by the last test in the new set of tests (also by the fuzz test), but I would like it if someone else could take a look at it because I don't fully understand the logic around `isPrefixMatching`.

**Comment by sgraf812** [comment]
Closed by #11.
